//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Applicatie_Risicoanalyse.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Applicatie_Risicoanalyse.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;acl&gt;
        ///	&lt;acl groupname=&quot;Default&quot;&gt;
        ///		&lt;right name=&quot;General.ButtonOpenAdminPanel&quot; access=&quot;none&quot;/&gt;
        ///	
        ///		&lt;right name=&quot;General.ButtonCreateProject&quot;  			access=&quot;none&quot;/&gt;
        ///		&lt;right name=&quot;General.ButtonOpenProject&quot; 			access=&quot;none&quot;/&gt;
        ///		&lt;right name=&quot;General.ButtonRecentProjects&quot; 			access=&quot;none&quot;/&gt;
        ///		&lt;right name=&quot;General.ButtonCreateProjectRevision&quot;	access=&quot;none&quot;/&gt;
        ///		&lt;right name=&quot;General.ButtonEditStandardRisks&quot; 		access=&quot;none&quot;/&gt;
        ///		&lt;right name=&quot;General.ButtonCreateNewRisk&quot;			access=&quot;none&quot;/&gt;
        ///		
        ///		&lt;right name=&quot;Ge [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ACL {
            get {
                return ResourceManager.GetString("ACL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Gotham_Light {
            get {
                object obj = ResourceManager.GetObject("Gotham_Light", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Langen_Group_Colour {
            get {
                object obj = ResourceManager.GetObject("Langen Group_Colour", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon MooreBrabazon_with_Flying_Pig {
            get {
                object obj = ResourceManager.GetObject("MooreBrabazon_with_Flying_Pig", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap MooreBrabazon_with_Flying_Pig1 {
            get {
                object obj = ResourceManager.GetObject("MooreBrabazon_with_Flying_Pig1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap NoRiskPicture {
            get {
                object obj = ResourceManager.GetObject("NoRiskPicture", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] PerformanceLevelFrontPageTemplate {
            get {
                object obj = ResourceManager.GetObject("PerformanceLevelFrontPageTemplate", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PerformanceLevelReportIcon {
            get {
                object obj = ResourceManager.GetObject("PerformanceLevelReportIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] PerformanceLevelRiskPageTemplate {
            get {
                object obj = ResourceManager.GetObject("PerformanceLevelRiskPageTemplate", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] RemainingRiskFrontPageTemplate {
            get {
                object obj = ResourceManager.GetObject("RemainingRiskFrontPageTemplate", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RemainingRiskReportIcon {
            get {
                object obj = ResourceManager.GetObject("RemainingRiskReportIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] RemainingRiskRiskPageHeaderTemplate {
            get {
                object obj = ResourceManager.GetObject("RemainingRiskRiskPageHeaderTemplate", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] RemainingRiskRiskPageTemplate {
            get {
                object obj = ResourceManager.GetObject("RemainingRiskRiskPageTemplate", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] RiskAssessmentFrontPageTemplate {
            get {
                object obj = ResourceManager.GetObject("RiskAssessmentFrontPageTemplate", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] RiskAssessmentIndexPageTemplate {
            get {
                object obj = ResourceManager.GetObject("RiskAssessmentIndexPageTemplate", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RiskAssessmentReportIcon {
            get {
                object obj = ResourceManager.GetObject("RiskAssessmentReportIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] RiskAssessmentRiskPageTemplate {
            get {
                object obj = ResourceManager.GetObject("RiskAssessmentRiskPageTemplate", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
